### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by benmerckx** [lix-pm/lix.client#128]
````
lix install gh:mvcoconut/coconut.h2d
````

results in:

````
TypeError: Cannot read property 'length' of undefined
    at Function.v.substr (C:\projects\test\node_modules\lix\bin\lix.js:2:99697)
    at C:\projects\test\node_modules\lix\bin\lix.js:2:193624
    at C:\projects\test\node_modules\lix\bin\lix.js:2:252928
    at Ye.f (C:\projects\test\node_modules\lix\bin\lix.js:2:153645)
    at Ye.get (C:\projects\test\node_modules\lix\bin\lix.js:2:251919)
    at Ee.f (C:\projects\test\node_modules\lix\bin\lix.js:2:247606)
    at Ee.handle (C:\projects\test\node_modules\lix\bin\lix.js:2:248769)
    at Ee.f (C:\projects\test\node_modules\lix\bin\lix.js:2:250261)
    at Ee.handle (C:\projects\test\node_modules\lix\bin\lix.js:2:248769)
    at C:\projects\test\node_modules\lix\bin\lix.js:2:250762
````
with 15.8.11

**Comment by benmerckx** [comment]
Makes me wonder why lix needs minification too?

**Comment by kevinresol** [comment]
Very likely the same as #123

**Comment by benmerckx** [comment]
Yep: https://github.com/MVCoconut/coconut.h2d/commit/7cc7605bc2c1acc48083a3da54fe64ba4c289803
