### ISSUE TITLE
lix vs. vshaxe's build-and-install

### ISSUE THREAD

**Issue by Simn** [lix-pm/lix.client#135]
Trying to run the `build-and-install (debug)` command in vshaxe fails with this error:

```
Error: Cannot find module 'minimist'
Require stack:
- C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at t.load (C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:119)
    at e.load (C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:586)
    at i (C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:29:189)
    at Object.errorback (C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:29:313)
    at e.triggerErrorback (C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:955)
    at C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:659
    at C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:494
    at u (C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:18:547)
    at ReadFileContext.callback (C:\Users\simn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:18:634)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\simn\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js',
    'C:\\Users\\simn\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js'
  ],
  phase: 'loading',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ]
}
```

The executed command is `npx lix run vshaxe-build --target build-and-install --debug --connect 6000`. Removing the `--connect 6000` and running it from the CLI makes it work.

**Comment by back2dos** [comment]
Soooo, it's a VSCode issue after all: https://github.com/Microsoft/vscode/issues/38428

When run via `--connect`, the final `Install.hx` runs with the environment passed down from VSCode, which has `ELECTRON_NO_ASAR` set to `1`. Effectively, this means that the almost 40MB big `/resources/app/node_modules.asar` in the bundle cannot be loaded and hence it attempts to get minimist in the normal fashion (and fails).

I suppose we can live with it. Or vshaxe could strip out the variable before invoking Haxe.
