### ISSUE TITLE
ReferenceError: sys is not defined

### ISSUE THREAD

**Issue by cedx** [lix-pm/lix.client#163]
Since lix 15.11.0, downloading the Haxe archive does not work anymore. Instead, I always get this error:

```
Looking up Haxe version "4.2.3" online
  Resolved to official release 4.2.3. Downloading ...
[...]
ReferenceError: sys is not defined
    at kt.linkToOfficial (C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:119838)
    at kt.download (C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:123104)
    at C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:121283
    at C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:133272
    at C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:132206
    at Object.zt.invoke (C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:126400)
    at Pt.invoke (C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:127962)
    at Xt.trigger (C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:131829)
    at Object.zt.invoke (C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:126400)
    at Pt.invoke (C:\Users\runneradmin\AppData\Local\Yarn\Data\global\node_modules\lix\bin\haxeshim.js:2:127962)
```

**Comment by kevinresol** [comment]
Caused by #158 , sys.io.Process is not defined in hxnodejs afaik. @dpomier any idea?

**Comment by kevinresol** [comment]
I don't understand. When would it get run in non-nodejs sys?

**Comment by back2dos** [comment]
Not in the near future, but since the code was already there, it was easy enough to handle the case.

**Comment by back2dos** [comment]
Yeah, it's a bit puzzling. I assumed he was locally using some (presumably fully blocking) `sys.io.Process` shim, but who knows ^^
