### ISSUE TITLE
Installing Haxe 4.2.4 fails

### ISSUE THREAD

**Issue by andraaspar** [lix-pm/lix.client#169]
Lix version: 15.11.3

```
$ lix download
Downloading Haxe: official release 4.2.4
-> Done!
node:internal/fs/utils:344
    throw err;
    ^

Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Roaming/haxe/downloads//4.2.4@1638895972206/haxe_20211022152000_ab0c054' -> 'C:\Users\username\AppData\Roaming/haxe/versions/4.2.4'
    at Object.renameSync (node:fs:980:3)
    at _n.replace (C:\projectname\node_modules\lix\bin\lix.js:2:223502)
    at C:\projectname\node_modules\lix\bin\lix.js:2:226472
    at C:\projectname\node_modules\lix\bin\lix.js:2:254513
    at C:\projectname\node_modules\lix\bin\lix.js:2:251816
    at Object.ue.invoke (C:\projectname\node_modules\lix\bin\lix.js:2:245878)
    at Se.invoke (C:\projectname\node_modules\lix\bin\lix.js:2:247794)
    at Ce.trigger (C:\projectname\node_modules\lix\bin\lix.js:2:252054)
    at Object.ue.invoke (C:\projectname\node_modules\lix\bin\lix.js:2:245878)
    at Se.invoke (C:\projectname\node_modules\lix\bin\lix.js:2:247794) {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\username\\AppData\\Roaming/haxe/downloads//4.2.4@1638895972206/haxe_20211022152000_ab0c054',
  dest: 'C:\\Users\\username\\AppData\\Roaming/haxe/versions/4.2.4'
}
```

**Comment by andraaspar** [comment]
Fun fact:
```js
import fs from 'fs';

fs.renameSync(
	'C:\\Users\\username\\AppData\\Roaming/haxe/downloads//4.2.4@1638895972206/haxe_20211022152000_ab0c054',
	'C:\\Users\\username\\AppData\\Roaming/haxe/versions/4.2.4'
);
```
This works when launched with `node test.mjs`.

**Comment by back2dos** [comment]
Is it possible you have an antivirus or some other service that might lock the directory shortly after its creation?

**Comment by andraaspar** [comment]
I tried it on another box and it worked seamlessly. I think you are right and McAfee antivirus may be the culprit.
