### ISSUE TITLE
ReferenceError: sys is not defined

### ISSUE THREAD

**Issue by cedx** [lix-pm/lix.client#170]
I've updated `lix` to v15.11.5... and now I get this error when downloading Haxe:

```
Looking up Haxe version "4.2.4" online
  Resolved to official release 4.2.4. Downloading ...
[...]
ReferenceError: sys is not defined
    at ie.linkToOfficial (C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:224684)
    at ie.download (C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:227952)
    at C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:226131
    at C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:256215
    at C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:254667
    at Object.be.invoke (C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:247580)
    at Be.invoke (C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:249496)
    at Ge.trigger (C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:254290)
    at Object.be.invoke (C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:247580)
    at Be.invoke (C:\Users\cedri\AppData\Roaming\npm\node_modules\lix\bin\lix.js:2:249496)
```

It seems that the latest `npm` release contains the PR #158... which was reverted by 7bbbcf275a7f971080d0455f006828f52ef1b5a8.

Node.js 17.2.0 on Windows 10

**Comment by kevinresol** [comment]
Can you please try again with v15.11.6?

**Comment by cedx** [comment]
It works! Thanks @kevinresol
