### ISSUE TITLE
"version" field in haxe.lib json is required now?

### ISSUE THREAD

**Issue by sh-dave** [lix-pm/lix.client#18]
Lix 0.9.1 crashes when installing a github library, and the haxelib.json doesn't contain a "version" field.
This didn't happen when i tried last time with lix version 0.4.0. It simply used 'undefined' as version i think.

### example
```sh
lix install gh:kevinresol/mongo
```

### output
```sh
downloading https://github.com/kevinresol/mongo/archive/6af4cdac0191b9066151d33893b2eb005c55af2e.tar.gz
C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:400
        return s.split(sub).join(by);
                ^

TypeError: Cannot read property 'split' of undefined
    at Function.StringTools.replace (C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:400:10)
    at lix_client_DownloadedArchive.escape (C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:2266:19)
    at Array.map (native)
    at Function.lix_client_DownloadedArchive.path (C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:2271:15)
    at Function.lix_client_DownloadedArchive.fresh (C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:2290:42)
    at C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:2621:45
    at C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:4627:10
    at C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:4353:11
    at tink_core__$Callback_ListCell.cb (C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:4508:5)
    at Object.tink_core__$Callback_CallbackList_$Impl_$.invoke (C:\Users\dklein\AppData\Roaming\npm\node_modules\lix.pm\bin\lix.js:4225:9)
```

**Comment by back2dos** [comment]
Works in 0.9.2 (tested with `lix install gh:kevinresol/mongo`).
