### ISSUE TITLE
lix install fails when haxelib.json has multiline releasenotes

### ISSUE THREAD

**Issue by AlexHaxe** [lix-pm/lix.client#197]
unfortunately https://github.com/ufront/ufront-easyauth/blob/master/haxelib.json has a mutliline `releasenote` field, so `lix install haxelib:ufront-easyauth` fails with
```
undefined:8
  "releasenote": "A 1.0.0 stable release.

SyntaxError: Unexpected token 
 in JSON at position 326
    at JSON.parse (<anonymous>)
    at mn.readInfos (/usr/lib/node_modules/lix/bin/lix.js:2:195705)
    at mn.existent (/usr/lib/node_modules/lix/bin/lix.js:2:194797)
    at /usr/lib/node_modules/lix/bin/lix.js:2:205401
    at /usr/lib/node_modules/lix/bin/lix.js:2:254453
    at /usr/lib/node_modules/lix/bin/lix.js:2:251756
    at ue.invoke (/usr/lib/node_modules/lix/bin/lix.js:2:245818)
    at Se.invoke (/usr/lib/node_modules/lix/bin/lix.js:2:247734)
    at Ce.trigger (/usr/lib/node_modules/lix/bin/lix.js:2:251994)
    at ue.invoke (/usr/lib/node_modules/lix/bin/lix.js:2:245818)
```

**Comment by kevinresol** [comment]
I'm not sure about this one... That's not even valid json. Imo haxelib should really have rejected it during submission.

I think I have access to merge a PR that fixes the json there, but probably I can't release to haxelib

**Comment by back2dos** [comment]
Yeah ... hmm ... I don't think we wanna fix this. It should be disabled in the stdlib and some script should be used to crawl and fix the affected zip archives on haxelib, which really shouldn't be that many. But let's see what happens with the issue I raised ^^
