### ISSUE TITLE
npm install lix seems to break everything

### ISSUE THREAD

**Issue by larsiusprime** [lix-pm/lix.client#39]
Sorry if I'm being dumb, but I recently tried to install lix and it seems to have broken quite a few things:

I opened a command line in Windows 10 and ran this:

```npm install --global lix```

Then I ran this:
```lix```

And got this:

```
C:\Users\Lars Doucet>lix
C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:1420
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at __dirname./PWO1pM5lLwyqdlyaovRHUOu+lELk9nNqLmH97GuFYg=.opt.filter.Promise.2AFNYz4lSXwSlQQf3/eWu6omuc8tXeaHDhk7oeZQsP4=.p.on.files.forEach.t.2qKOuoyDrIbn3tXU28MnQI6TzoWc0B5TyIq68LcLqd4=.opt.onentry.opt.filter.p.3cvmAZk8FK1SBh8Ge8NUCWlDUWArxUeTcVe2v8XYctY=.Parser.constructor.opt.ondone.stream.on.stream.on.entry.(anonymous function).entry.(anonymous function).fs.lstat.Unpack.4Qo/V2sAfYSCXwRWGyedb6H4upRdwnVV4faxt79hltM=.module.exports.fs.lstat.56qWjByKztF5uZPT3/DJRKRxgtAKle3Xm5h2aKcXSRU=.MiniPass.constructor.opt.zip.on.zip.on.zip.on.on.job.(anonymous function).on.job.readdir.forEach (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:1420:20)
    at load (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:14:5)
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:17:29
    at __dirname./PWO1pM5lLwyqdlyaovRHUOu+lELk9nNqLmH97GuFYg=.opt.filter.Promise.2AFNYz4lSXwSlQQf3/eWu6omuc8tXeaHDhk7oeZQsP4=.p.on.files.forEach.createSync (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:167:14)
    at load (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:14:5)
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:17:29
    at __dirname./PWO1pM5lLwyqdlyaovRHUOu+lELk9nNqLmH97GuFYg=.opt.filter.Promise.2AFNYz4lSXwSlQQf3/eWu6omuc8tXeaHDhk7oeZQsP4=.p.on.files.forEach.t.2qKOuoyDrIbn3tXU28MnQI6TzoWc0B5TyIq68LcLqd4=.opt.onentry.opt.filter.p.3cvmAZk8FK1SBh8Ge8NUCWlDUWArxUeTcVe2v8XYctY=.Parser.constructor.opt.ondone.stream.on.stream.on.entry.(anonymous function).entry.(anonymous function).fs.lstat.Unpack.4Qo/V2sAfYSCXwRWGyedb6H4upRdwnVV4faxt79hltM=.module.exports.fs.lstat.56qWjByKztF5uZPT3/DJRKRxgtAKle3Xm5h2aKcXSRU=.MiniPass.constructor.opt.zip.on.zip.on.zip.on.on.job.(anonymous function).on.job.IHzFTXFK768mHhaTa50fJLoNbqriK7aGJ03V/M/piPo=.padOctal.IRCPAQdxxTPxDSNVEjbpJrDey6YtBZTsHyHy3quzDzk=.module.exports.SX9P+POf3/GXLCE0cLDxEkkQ4tPflmjCjO2alrFH938=.EE.set.enc.pipe.opts.emit.data.hWgHoyC4ICUyk4ZXQMqKFVM8HT2nRBT3U8d54EJfPVM=.hmnRD7etIIKY8nGARtOEtPwLHJ5n8EdTamzJ/6pL3mg=.parse.i0E8knuUHabWe79/B8YbGgCVTW4N43yTAuri+/11BNk=.p.on.files.forEach.addFilesAsync.mf8OAFaZOMvEeUCmNGD49bLJuxVBwZ7aQi9fSVkX2Xs=.MiniPass.nB1sORH0sHB3HwuVwSIfqP+HqxiOeLKDcklHFiMBvGk=.qf32nrRJcz5ulBOhqaOhbRFR1PGe8tScTbGJRKCNRk0=.Pax.parse.merge.rShkRzOhrA698Po52a5kgqfF/najh4ymb9PcXu4a8ec= (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:12856:30)
    at load (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:14:5)
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:17:29
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\lix.js:7302:38

C:\Users\Lars Doucet>
```

Did I do something obviously wrong?

**Comment by larsiusprime** [comment]
Also, running "haxe" command now generates this:

```
C:\Users\Lars Doucet>haxe
C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:1420
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at __dirname./PWO1pM5lLwyqdlyaovRHUOu+lELk9nNqLmH97GuFYg=.opt.filter.Promise.2AFNYz4lSXwSlQQf3/eWu6omuc8tXeaHDhk7oeZQsP4=.p.on.files.forEach.t.2qKOuoyDrIbn3tXU28MnQI6TzoWc0B5TyIq68LcLqd4=.opt.onentry.opt.filter.p.3cvmAZk8FK1SBh8Ge8NUCWlDUWArxUeTcVe2v8XYctY=.Parser.constructor.opt.ondone.stream.on.stream.on.entry.(anonymous function).entry.(anonymous function).fs.lstat.Unpack.4Qo/V2sAfYSCXwRWGyedb6H4upRdwnVV4faxt79hltM=.module.exports.fs.lstat.56qWjByKztF5uZPT3/DJRKRxgtAKle3Xm5h2aKcXSRU=.MiniPass.constructor.opt.zip.on.zip.on.zip.on.on.job.(anonymous function).on.job.readdir.forEach (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:1420:20)
    at load (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:14:5)
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:17:29
    at __dirname./PWO1pM5lLwyqdlyaovRHUOu+lELk9nNqLmH97GuFYg=.opt.filter.Promise.2AFNYz4lSXwSlQQf3/eWu6omuc8tXeaHDhk7oeZQsP4=.p.on.files.forEach.createSync (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:167:14)
    at load (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:14:5)
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:17:29
    at __dirname./PWO1pM5lLwyqdlyaovRHUOu+lELk9nNqLmH97GuFYg=.opt.filter.Promise.2AFNYz4lSXwSlQQf3/eWu6omuc8tXeaHDhk7oeZQsP4=.p.on.files.forEach.t.2qKOuoyDrIbn3tXU28MnQI6TzoWc0B5TyIq68LcLqd4=.opt.onentry.opt.filter.p.3cvmAZk8FK1SBh8Ge8NUCWlDUWArxUeTcVe2v8XYctY=.Parser.constructor.opt.ondone.stream.on.stream.on.entry.(anonymous function).entry.(anonymous function).fs.lstat.Unpack.4Qo/V2sAfYSCXwRWGyedb6H4upRdwnVV4faxt79hltM=.module.exports.fs.lstat.56qWjByKztF5uZPT3/DJRKRxgtAKle3Xm5h2aKcXSRU=.MiniPass.constructor.opt.zip.on.zip.on.zip.on.on.job.(anonymous function).on.job.IHzFTXFK768mHhaTa50fJLoNbqriK7aGJ03V/M/piPo=.padOctal.IRCPAQdxxTPxDSNVEjbpJrDey6YtBZTsHyHy3quzDzk=.module.exports.SX9P+POf3/GXLCE0cLDxEkkQ4tPflmjCjO2alrFH938=.EE.set.enc.pipe.opts.emit.data.hWgHoyC4ICUyk4ZXQMqKFVM8HT2nRBT3U8d54EJfPVM=.hmnRD7etIIKY8nGARtOEtPwLHJ5n8EdTamzJ/6pL3mg=.parse.i0E8knuUHabWe79/B8YbGgCVTW4N43yTAuri+/11BNk=.p.on.files.forEach.addFilesAsync.mf8OAFaZOMvEeUCmNGD49bLJuxVBwZ7aQi9fSVkX2Xs=.MiniPass.nB1sORH0sHB3HwuVwSIfqP+HqxiOeLKDcklHFiMBvGk=.qf32nrRJcz5ulBOhqaOhbRFR1PGe8tScTbGJRKCNRk0=.Pax.parse.merge.rShkRzOhrA698Po52a5kgqfF/najh4ymb9PcXu4a8ec= (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:9118:30)
    at load (C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:14:5)
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:17:29
    at C:\Users\Lars Doucet\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:5189:38

C:\Users\Lars Doucet>
```

Maybe an issue with haxeshim?

**Comment by kevinresol** [comment]
What is your node version?

**Comment by larsiusprime** [comment]
Looks like v4.3.2 -- I don't use node.js / npm much. Should I just upgrade node? If so, to which version?

**Comment by kevinresol** [comment]
It fails because Buffer.alloc was added in v5. I usually use v6 on my CIs.

**Comment by larsiusprime** [comment]
Thanks!

**Comment by larsiusprime** [comment]
Works now! Sorry I'm silly and dumb :P 

I suppose one could list a minimum required version of node/npm on the readme?

**Comment by back2dos** [comment]
Reopening, so I don't forget about that :D
