### ISSUE TITLE
haxe 4 preview 4 issue

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/lix.client#44]
```haxe
class Main {
    static function main() {
        var name = 'Foo';
        trace('${name}');
    }
}
```

Try to trigger code completion anywhere in the above code:

```
Haxe language server started
Listening on port 6004
Building Cache...
Parsing Classpaths...
Done.

(triggered)

Haxe server restart requested: Haxe process was killed
Restarted Haxe server: Haxe process was killed
Building Cache...
Parsing Classpaths...
Done.

(triggered)

Haxe server restart requested: Haxe process was killed
Restarted Haxe server: Haxe process was killed
Building Cache...
Parsing Classpaths...
Done.

(triggered)

Error message from the compiler:

ers/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:3774
					throw new js__$Boot_HaxeError("unknown variable " + name);
					^
Error: unknown variable name
    at Function.DwVIsOsueSK3bnvdZSxLjXktoi3h6HfPjLbDQVj8wSE=.haxeshim_Resolver.interpolate (/Users/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:3774:12)
    at haxeshim_Resolver.process (/Users/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:3945:30)
    at haxeshim_Resolver.resolve (/Users/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:3850:8)
    at haxeshim_Scope.resolve (/Users/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:3715:24)
    at processData (/Users/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:2750:88)
    at reduce (/Users/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:2772:7)
    at Socket.<anonymous> (/Users/kevin/.config/yarn/global/node_modules/lix/bin/haxeshim.js:2799:4)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

The first two triggers will kill the server.
The third trigger crashes with an error `unknown variable name` which is due to haxeshim somehow trying to parse the Haxe expr and resolve the `name` variable as env var.

**Comment by benmerckx** [comment]
This does appear to still be happening for me with lix 15.3.5. Does the vshaxe completion send the whole source as a command line argument somehow?

**Comment by kevinresol** [comment]
Iirc yes it does send the source

**Comment by benmerckx** [comment]
It could not throw if the environment var is not found, but that would mess up completion too if accidentally it was found. Possible work around is not interpolating arguments after "--display" if I read vshaxe sources correctly but it's a little messy and not very future proof. Then again having this fail in any file that uses `'${...}'` interpolation is tiring.

**Comment by benmerckx** [comment]
See https://github.com/lix-pm/haxeshim/pull/33

**Comment by kevinresol** [comment]
Is this still a problem?

**Comment by back2dos** [comment]
I guess Ben's workaround fixed this.
