### ISSUE TITLE
npm uninstall --global lix should restore previous environment

### ISSUE THREAD

**Issue by joshtynjala** [lix-pm/lix.client#91]
I had to install Lix temporarily for a project, and when I uninstalled it later, everything was broken. Running the haxe or haxelib command in my terminal gives me this error:

```
PS C:\Users\josht> haxe
internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module 'C:\Users\josht\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
      at Function.Module._load (internal/modules/cjs/loader.js:618:27)
      at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
      at internal/main/run_main_module.js:17:11 {
    code: 'MODULE_NOT_FOUND',
    requireStack: []
}
```
It would be nice if lix could restore everything back to its original state when I uninstall it.

**Comment by al-arz** [comment]
Seems related: https://github.com/lix-pm/haxeshim/issues/23

**Comment by Gama11** [comment]
This is part of the reason I only use local Lix installations.

**Comment by joshtynjala** [comment]
Yeah, a local installation seems to work well. Unfortunately, I didn't discover that it was an option until after I had used a global installation and messed up my existing environment. 😢
